# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 05:45
from __future__ import unicode_literals

import Summarizer.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Summarizer', '0002_auto_20171109_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getfile',
            name='file',
            field=models.FileField(upload_to='', validators=[Summarizer.validators.validate_file_extension]),
        ),
    ]
