# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Summarizer', '0003_auto_20171109_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='getfile',
            name='user',
            field=models.CharField(default='', max_length=50),
        ),
    ]
