# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Summarizer', '0004_getfile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getfile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='getfile',
            name='name',
        ),
    ]
